server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: ${ERROR_STACKTRACE:always}
    include-message: ${ERROR_MESSAGE:always}

spring:
  application:
    name: readingtrace
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: ${ANSI_ENABLED:always}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/readingtrace}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}

#actuator
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:always}
    env:
      show-values: ${ACTUATOR_SHOW_VALUES:always}
  security:
    enabled: ${ACTUATOR_SECURITY:false}

logging:
  level:
    org.springframework.security:  ${SECURITY_LOG_LEVEL:TRACE}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_PARAM_LOG:TRACE}
    com.yurakim.readingtrace: ${APP_LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_FILE:}
  pattern:
    file: ${LOG_PATTERN:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}