//static
export const BookCollection = [
  {
    bookId: 1000000001,
    externalId: 'RT1000000001',
    title: 'A Clockwork Orange',
    authors: ['Anthony Burgess'],
    imageLinks: '/a_clockwork_orange.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000002,
    externalId: 'RT1000000002',
    title: 'Cats Cradle',
    authors: ['Kurt Vonnegut'],
    imageLinks: '/cats_cradle.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000003,
    externalId: 'RT1000000003',
    title: 'Metamorphosis',
    authors: ['Franz Kafka'],
    imageLinks: '/metamorphosis.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000004,
    externalId: 'RT1000000004',
    title: 'Of Human Bondage',
    authors: ['W. Somerset Maugham'],
    imageLinks: '/of_human_bondage.jpg',
    description: `A masterpiece of modern literature that mirrors Maugham's own career. Of Human Bondage is the first and most autobiographical of Maugham's novels. It is the story of Philip Carey, an orphan eager for life, love and adventure. After a few months studying in Heidelberg, and a brief spell in Paris as a would-be artist, Philip settles in London to train as a doctor. And that is where he meets Mildred, the loud but irresistible waitress with whom he plunges into a formative, tortured and masochistic affair which very nearly ruins him.`,
    publishedDate: 'February 23, 2010',
    publisher: 'Random House',
    isbn10: '1407016458',
    isbn13: '9781407016450',
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000005,
    externalId: 'RT1000000005',
    title: 'Slaughterhouse Five',
    authors: ['Kurt Vonnegut'],
    imageLinks: '/slaughterhouse_five.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000006,
    externalId: 'RT1000000006',
    title: 'Steeppenwolf',
    authors: ['Hermann Hesse'],
    imageLinks: '/steppenwolf.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000007,
    externalId: 'RT1000000007',
    title: 'The Bhagavad Gita',
    authors: ['N/A'],
    imageLinks: '/the_bhagavad_gita.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000008,
    externalId: 'RT1000000008',
    title: 'The Castle',
    authors: ['Franz Kafka'],
    imageLinks: '/the_castle.jpg',
    publisher: null,
    publishedDate: null,
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
  {
    bookId: 1000000009,
    externalId: 'RT1000000009',
    title: 'The Trial',
    authors: ['Franz Kafka'],
    publisher: 'Penguin Books Ltd (UK)',
    publishedDate: '2024',
    imageLinks: '/the_trial.jpg',
    description: null,
    isbn10: null,
    isbn13: null,
    pageCount: null,
    mainCategory: null,
    categories: null,
    averageRating: null,
    ratingsCount: null,
    language: 'en',
  },
];
